ignore:
  # For grype configuration, see https://github.com/anchore/grype#specifying-matches-to-ignore

  # https://github.com/advisories/GHSA-w32m-9786-jp63
  # Per upstream Kubernetes developers, kubectl is not impacted by this vuln https://github.com/kubernetes/kubernetes/issues/129412
  - vulnerability: GHSA-w32m-9786-jp63
    package:
      location: /usr/local/bin/kubectl


