ignore:
  # For grype configuration, see https://github.com/anchore/grype#specifying-matches-to-ignore
    
  - vulnerability: GHSA-hqxw-f8mx-cpmw
    fix-state: "not-fixed"

  - package:
      location: /usr/local/bin/kubectl
