ignore:
  # For grype configuration, see https://github.com/anchore/grype#specifying-matches-to-ignore

  # https://nvd.nist.gov/vuln/detail/CVE-2024-34156
  # Expecting upstream fix in next patch build of kubectl executable
  - vulnerability: CVE-2024-34156
    package:
      location: /usr/local/bin/kubectl

  # https://nvd.nist.gov/vuln/detail/CVE-2024-34158
  # Expecting upstream fix in next patch build of kubectl executable
  - vulnerability: CVE-2024-34158
    package:
      location: /usr/local/bin/kubectl


