ignore:
  # For grype configuration, see https://github.com/anchore/grype#specifying-matches-to-ignore

  # This is part of the kubectl executable.  It will be included in this
  # docker image when the authors of kubectl adopt the fix for this issue.
  - vulnerability: GHSA-hqxw-f8mx-cpmw
    fix-state: "not-fixed"

  #- package:
  #    location: /usr/local/bin/kubectl
  
  - vulnerability: GHSA-f4w6-3rh6-6q4q-k8s.io/kubernetes
    fix-state: not-fixed
    package:
      name: github.com/docker/distribution
      version: v2.8.1+incompatible
      location: /usr/local/bin/kubectl
